name: Create IssueOps Labels

on:
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  label:
    name: Create IssueOps Labels
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get the data file.
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      # Read the data file to get the list of labels, then create any that are
      # missing from the IssueOps repository.
      - name: Create Missing Labels
        id: read
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const labels = JSON.parse(
              fs.readFileSync(
                path.join(
                  process.env.GITHUB_WORKSPACE,
                  'data',
                  'issue-ops.json'
                ), 'utf8'
              )
            ).map((issueOp) => (issueOp.label));

            for (const label of ['issue-ops', ...labels]) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label
                });
              } catch (error) {
                if (error.status !== 422) {
                  throw error;
                }
              }
            }
